/*
 * StdoutView.java
 *
 * Created on June 1, 2007, 1:06 PM
 */

package com.wms.logos.iframe.gui;

import com.wms.logos.icomponent.IComponentInterface;
import javax.swing.JPanel;
import javax.swing.JViewport;

/**
 *
 * @author  mstemen
 */
public class StdoeVue extends javax.swing.JPanel implements VueInterface
{
    private String viewTitle = "Cmdline View";
    /** Creates new form StdoutView */
    public StdoeVue()
    {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        statusCount = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        alertCount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        stdoutPane = new javax.swing.JTextPane();

        setLayout(new java.awt.GridLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 153));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel2.setBackground(new java.awt.Color(204, 153, 0));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 11));
        jLabel1.setText("Stdout/err");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 59);
        jPanel2.add(jLabel1, gridBagConstraints);

        jPanel3.setLayout(new java.awt.GridLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("stdout:");
        jPanel3.add(jLabel2);

        statusCount.setText("0");
        jPanel3.add(statusCount);

        jLabel3.setText("stderr");
        jPanel3.add(jLabel3);

        alertCount.setText("0");
        jPanel3.add(alertCount);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 77, 2, 0);
        jPanel2.add(jPanel3, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        stdoutPane.setBackground(new java.awt.Color(255, 255, 244));
        stdoutPane.setEditable(false);
        stdoutPane.setMinimumSize(new java.awt.Dimension(600, 600));
        jScrollPane1.setViewportView(stdoutPane);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel1);

    }// </editor-fold>//GEN-END:initComponents

    public void fwWrite(String message)
    {
    }

    public void fwWriteStatus(String message)
    {
    }

    public void clear()
    {
    }

    public void writeln(String message)
    {
    }

    public void write(String[] messages)
    {
    }

    public JViewport getViewPort()
    {
        return this.getViewPort();
    }

    public JPanel getPanel()
    {
        return this;
    }

    public String fwGetName()
    {
        return "stdoe";
    }

    public IComponentInterface fwGetRoute()
    {
        return this;
    }

    public void fwWriteStatus(Exception e)
    {
    }

    public void writeSpecial(String message)
    {
    }

    public void fwWrite(String msg, String target) throws FWTargetException
    {
    }

    public void fwWrite(Exception e)
    {
    }

    public void fwWrite(Exception e, String target) throws FWTargetException
    {
    }

    public void fwWrite(FWWriteLevel level, String msg)
    {
    }

    public void fwWrite(FWWriteLevel level, String msg, String target) throws FWTargetException
    {
    }

    public void fwWrite(FWWriteLevel level, Exception e)
    {
    }

    public void fwWrite(FWWriteLevel level, Exception e, String target) throws FWTargetException
    {
    }

    public String getTitle()
    {
        return viewTitle;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alertCount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel statusCount;
    private javax.swing.JTextPane stdoutPane;
    // End of variables declaration//GEN-END:variables
    
}
