/*
 * TestVue.java
 *
 * Created on May 25, 2007, 2:57 PM
 */

package com.wms.logos.iframe.gui;


import com.wms.logos.icomponent.IComponentInterface;
import javax.swing.JPanel;
import javax.swing.JViewport;

/**
 *
 * @author  mstemen
 */
public class TestVue extends javax.swing.JPanel implements VueInterface
{
    
    private String viewTitle = "Test View";
    /**
     * Creates new form TestVue
     */
    public TestVue()
    {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setLayout(new java.awt.BorderLayout());

        setBackground(new java.awt.Color(0, 102, 102));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel2.setText("Test View 1");
        jPanel2.add(jLabel2);

        add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48));
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("Just a Test");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 13, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jProgressBar1.setIndeterminate(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 0, 0);
        jPanel1.add(jProgressBar1, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    public void fwWrite(String message)
    {
    }

    public void fwWriteStatus(String message)
    {
    }

    public void clear()
    {
    }

    public void writeln(String message)
    {
    }

    public void write(String[] messages)
    {
    }

    public JViewport getViewPort()
    {
        return null;
    }

    public JPanel getPanel()
    {
        return this;
    }

    public String fwGetName()
    {
        return("test");
    }

    public IComponentInterface fwGetRoute()
    {
        return this;
    }

    public void fwWriteStatus(Exception e)
    {
    }

    public void writeSpecial(String message)
    {
    }

    public void fwWrite(String msg, String target) throws FWTargetException
    {
    }

    public void fwWrite(Exception e)
    {
    }

    public void fwWrite(Exception e, String target) throws FWTargetException
    {
    }

    public void fwWrite(FWWriteLevel level, String msg)
    {
    }

    public void fwWrite(FWWriteLevel level, String msg, String target) throws FWTargetException
    {
    }

    public void fwWrite(FWWriteLevel level, Exception e)
    {
    }

    public void fwWrite(FWWriteLevel level, Exception e, String target) throws FWTargetException
    {
    }

    public String getTitle()
    {
        return viewTitle;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
    
}
